=== beyond-aion/aion-server/game-server/data/static_data/vortex/dimensional_vortex.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
		   jxb:version="2.1">
	<xs:include schemaLocation="../global_types.xsd"/>
	<xs:element name="dimensional_vortex">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="vortex_location" type="Vortex" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Vortex">
		<xs:sequence>
			<xs:element name="home_point" type="HomePoint" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="resurrection_point" type="ResurrectionPoint" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="start_point" type="StartPoint" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required"/>
		<xs:attribute name="defends_race" type="Race"/>
		<xs:attribute name="offence_race" type="Race"/>
		<xs:attribute name="zones" type="StringListType" use="required"/>
	</xs:complexType>
	<xs:complexType name="HomePoint">
		<xs:attribute name="map" type="xs:int" use="required"/>
		<xs:attribute name="x" type="xs:float" use="required"/>
		<xs:attribute name="y" type="xs:float" use="required"/>
		<xs:attribute name="z" type="xs:float" use="required"/>
		<xs:attribute name="h" type="xs:byte" use="required"/>
	</xs:complexType>
	<xs:complexType name="ResurrectionPoint">
		<xs:attribute name="map" type="xs:int" use="required"/>
		<xs:attribute name="x" type="xs:float" use="required"/>
		<xs:attribute name="y" type="xs:float" use="required"/>
		<xs:attribute name="z" type="xs:float" use="required"/>
		<xs:attribute name="h" type="xs:byte" use="required"/>
	</xs:complexType>
	<xs:complexType name="StartPoint">
		<xs:attribute name="map" type="xs:int" use="required"/>
		<xs:attribute name="x" type="xs:float" use="required"/>
		<xs:attribute name="y" type="xs:float" use="required"/>
		<xs:attribute name="z" type="xs:float" use="required"/>
		<xs:attribute name="h" type="xs:byte" use="required"/>
	</xs:complexType>
</xs:schema>

=== beyond-aion/aion-server/game-server/data/static_data/vortex/dimensional_vortex.xml
<?xml version="1.0" encoding="UTF-8"?>
<dimensional_vortex xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dimensional_vortex.xsd">
	<vortex_location id="0" defends_race="ELYOS" offence_race="ASMODIANS" zones="JAMANOK_INN_210060000 THE_STALKING_GROUNDS_210060000 BLACK_ROCK_HOT_SPRING_210060000 FREGIONS_FLAME_210060000">
		<home_point map="120080000" x="559.4" y="207.8" z="93.5" h="0"/>
		<resurrection_point map="210060000" x="951.0" y="2433.0" z="107.0" h="0"/>
		<start_point map="210060000" x="951.0" y="2433.0" z="107.0" h="0"/>
	</vortex_location>
	<vortex_location id="1" defends_race="ASMODIANS" offence_race="ELYOS" zones="WAILING_CLIFFS_220050000 BALTASAR_CEMETERY_220050000 THE_LEGEND_SHRINE_220050000 SUDORVILLE_220050000 BALTASAR_HILL_VILLAGE_220050000 BRUSTHONIN_MITHRIL_MINE_220050000">
		<home_point map="110070000" x="452.6" y="237.1" z="127.0" h="0"/>
		<resurrection_point map="220050000" x="2237.3" y="2801.5" z="73.3" h="0"/>
		<start_point map="220050000" x="2242.0" y="2797.0" z="75.4" h="0"/>
	</vortex_location>
</dimensional_vortex>
