=== beyond-aion/aion-server/game-server/data/static_data/exp_mod_table/mentee_exp_limit_table.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="mentee_exp_limit_table">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="level" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="lvl" type="xs:int" use="required"/>
						<xs:attribute name="exp_limit" type="xs:long" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== beyond-aion/aion-server/game-server/data/static_data/exp_mod_table/mentee_exp_limit_table.xml
<?xml version="1.0" encoding="UTF-8"?>
<mentee_exp_limit_table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mentee_exp_limit_table.xsd">
	<level lvl="1" exp_limit="193"/>
	<level lvl="2" exp_limit="284"/>
	<level lvl="3" exp_limit="418"/>
	<level lvl="4" exp_limit="561"/>
	<level lvl="5" exp_limit="721"/>
	<level lvl="6" exp_limit="918"/>
	<level lvl="7" exp_limit="1127"/>
	<level lvl="8" exp_limit="1389"/>
	<level lvl="9" exp_limit="1696"/>
	<level lvl="10" exp_limit="2007"/>
	<level lvl="11" exp_limit="2362"/>
	<level lvl="12" exp_limit="2761"/>
	<level lvl="13" exp_limit="3286"/>
	<level lvl="14" exp_limit="3782"/>
	<level lvl="15" exp_limit="4230"/>
	<level lvl="16" exp_limit="4896"/>
	<level lvl="17" exp_limit="5482"/>
	<level lvl="18" exp_limit="6185"/>
	<level lvl="19" exp_limit="6923"/>
	<level lvl="20" exp_limit="7704"/>
	<level lvl="21" exp_limit="8847"/>
	<level lvl="22" exp_limit="10025"/>
	<level lvl="23" exp_limit="11575"/>
	<level lvl="24" exp_limit="13047"/>
	<level lvl="25" exp_limit="14517"/>
	<level lvl="26" exp_limit="16589"/>
	<level lvl="27" exp_limit="18450"/>
	<level lvl="28" exp_limit="20680"/>
	<level lvl="29" exp_limit="23271"/>
	<level lvl="30" exp_limit="26019"/>
	<level lvl="31" exp_limit="29125"/>
	<level lvl="32" exp_limit="32466"/>
	<level lvl="33" exp_limit="36805"/>
	<level lvl="34" exp_limit="40804"/>
	<level lvl="35" exp_limit="45480"/>
	<level lvl="36" exp_limit="51335"/>
	<level lvl="37" exp_limit="56799"/>
	<level lvl="38" exp_limit="63616"/>
	<level lvl="39" exp_limit="70913"/>
	<level lvl="40" exp_limit="79275"/>
	<level lvl="41" exp_limit="84129"/>
	<level lvl="42" exp_limit="89730"/>
	<level lvl="43" exp_limit="95459"/>
	<level lvl="44" exp_limit="100744"/>
	<level lvl="45" exp_limit="107044"/>
	<level lvl="46" exp_limit="113949"/>
	<level lvl="47" exp_limit="119860"/>
	<level lvl="48" exp_limit="126353"/>
	<level lvl="49" exp_limit="133552"/>
	<level lvl="50" exp_limit="141004"/>
	<level lvl="51" exp_limit="148052"/>
	<level lvl="52" exp_limit="155458"/>
	<level lvl="53" exp_limit="163231"/>
	<level lvl="54" exp_limit="171389"/>
	<level lvl="55" exp_limit="179960"/>
	<level lvl="56" exp_limit="188959"/>
	<level lvl="57" exp_limit="198406"/>
	<level lvl="58" exp_limit="208327"/>
	<level lvl="59" exp_limit="218742"/>
	<level lvl="60" exp_limit="229681"/>
	<level lvl="61" exp_limit="241164"/>
	<level lvl="62" exp_limit="253222"/>
	<level lvl="63" exp_limit="265882"/>
	<level lvl="64" exp_limit="279178"/>
	<level lvl="65" exp_limit="293138"/>
	<level lvl="66" exp_limit="307792"/>
	<level lvl="67" exp_limit="323183"/>
	<level lvl="68" exp_limit="339341"/>
	<level lvl="69" exp_limit="356310"/>
	<level lvl="70" exp_limit="374127"/>
	<level lvl="71" exp_limit="392831"/>
	<level lvl="72" exp_limit="412472"/>
	<level lvl="73" exp_limit="433098"/>
	<level lvl="74" exp_limit="454753"/>
	<level lvl="75" exp_limit="477488"/>
	<level lvl="76" exp_limit="501365"/>
	<level lvl="77" exp_limit="526430"/>
	<level lvl="78" exp_limit="552752"/>
	<level lvl="79" exp_limit="580390"/>
	<level lvl="80" exp_limit="609409"/>
	<level lvl="81" exp_limit="639881"/>
	<level lvl="82" exp_limit="671874"/>
	<level lvl="83" exp_limit="705468"/>
	<level lvl="84" exp_limit="740743"/>
	<level lvl="85" exp_limit="777777"/>
	<level lvl="86" exp_limit="816667"/>
	<level lvl="87" exp_limit="857501"/>
	<level lvl="88" exp_limit="900375"/>
	<level lvl="89" exp_limit="945394"/>
	<level lvl="90" exp_limit="992665"/>
	<level lvl="91" exp_limit="1042298"/>
	<level lvl="92" exp_limit="1094414"/>
	<level lvl="93" exp_limit="1149134"/>
	<level lvl="94" exp_limit="1206589"/>
	<level lvl="95" exp_limit="1266918"/>
	<level lvl="96" exp_limit="1330267"/>
	<level lvl="97" exp_limit="1396779"/>
	<level lvl="98" exp_limit="1466620"/>
	<level lvl="99" exp_limit="1539948"/>
	<level lvl="100" exp_limit="1616948"/>
</mentee_exp_limit_table>
