=== beyond-aion/aion-server/game-server/data/static_data/exp_mod_table/party_exp_mod_table.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../global_types.xsd" />
	<xs:element name="party_exp_mod_table">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="level_diff_mod" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="level_diff" type="xs:int" use="required"/>
						<xs:attribute name="mods" type="IntListType" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== beyond-aion/aion-server/game-server/data/static_data/exp_mod_table/party_exp_mod_table.xml
<?xml version="1.0" encoding="UTF-8"?>
<party_exp_mod_table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="party_exp_mod_table.xsd">
	<level_diff_mod level_diff="0" mods="2000 2000 2000 2000 2000 2000 2000 2000"/>
	<level_diff_mod level_diff="1" mods="1715 1900 1900 1900 1900 1900 1900 1900"/>
	<level_diff_mod level_diff="2" mods="1430 1825 1825 1825 1825 1825 1825 1825"/>
	<level_diff_mod level_diff="3" mods="1145 1650 1650 1650 1650 1650 1650 1650"/>
	<level_diff_mod level_diff="4" mods="860 1480 1480 1480 1480 1480 1480 1480"/>
	<level_diff_mod level_diff="5" mods="430 1320 1320 1320 1320 1320 1320 1320"/>
	<level_diff_mod level_diff="6" mods="215 1200 1200 1200 1200 1200 1200 1200"/>
	<level_diff_mod level_diff="7" mods="107 1020 1020 1020 1020 1020 1020 1020"/>
	<level_diff_mod level_diff="8" mods="53 920 920 920 920 920 920 920"/>
	<level_diff_mod level_diff="9" mods="26 860 860 860 860 860 860 860"/>
	<level_diff_mod level_diff="10" mods="21 800 800 800 800 800 800 800"/>
	<level_diff_mod level_diff="11" mods="1 360 360 360 360 360 360 360"/>
	<level_diff_mod level_diff="12" mods="1 60 60 60 60 60 60 60"/>
	<level_diff_mod level_diff="13" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="14" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="15" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="16" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="17" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="18" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="19" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="20" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="21" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="22" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="23" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="24" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="25" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="26" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="27" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="28" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="29" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="30" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="31" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="32" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="33" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="34" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="35" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="36" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="37" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="38" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="39" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="40" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="41" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="42" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="43" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="44" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="45" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="46" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="47" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="48" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="49" mods="1 1 1 1 1 1 1 1"/>
	<level_diff_mod level_diff="50" mods="1 1 1 1 1 1 1 1"/>
</party_exp_mod_table>
