=== beyond-aion/aion-server/game-server/data/static_data/exp_mod_table/pvp_exp_table.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="pvp_exp_table">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="level" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="lvl" type="xs:int" use="required"/>
						<xs:attribute name="exp" type="xs:int" use="required"/>
						<xs:attribute name="get_max_from_all_user" type="xs:int" use="required"/>
						<xs:attribute name="get_max_reduce_amount" type="xs:int" use="required"/>
						<xs:attribute name="get_max_reduce_interval" type="xs:int" use="required"/>
						<xs:attribute name="delay_time" type="xs:int" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== beyond-aion/aion-server/game-server/data/static_data/exp_mod_table/pvp_exp_table.xml
<?xml version="1.0" encoding="UTF-8"?>
<pvp_exp_table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pvp_exp_table.xsd">
	<level lvl="1" exp="0" get_max_from_all_user="0" get_max_reduce_amount="0" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="2" exp="0" get_max_from_all_user="0" get_max_reduce_amount="0" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="3" exp="0" get_max_from_all_user="0" get_max_reduce_amount="0" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="4" exp="0" get_max_from_all_user="0" get_max_reduce_amount="0" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="5" exp="0" get_max_from_all_user="0" get_max_reduce_amount="0" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="6" exp="0" get_max_from_all_user="0" get_max_reduce_amount="0" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="7" exp="0" get_max_from_all_user="0" get_max_reduce_amount="0" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="8" exp="0" get_max_from_all_user="0" get_max_reduce_amount="0" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="9" exp="0" get_max_from_all_user="0" get_max_reduce_amount="0" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="10" exp="0" get_max_from_all_user="520" get_max_reduce_amount="520" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="11" exp="0" get_max_from_all_user="612" get_max_reduce_amount="612" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="12" exp="0" get_max_from_all_user="716" get_max_reduce_amount="716" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="13" exp="0" get_max_from_all_user="852" get_max_reduce_amount="852" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="14" exp="0" get_max_from_all_user="980" get_max_reduce_amount="980" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="15" exp="0" get_max_from_all_user="1097" get_max_reduce_amount="1097" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="16" exp="1269" get_max_from_all_user="1269" get_max_reduce_amount="1269" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="17" exp="1421" get_max_from_all_user="1421" get_max_reduce_amount="1421" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="18" exp="1603" get_max_from_all_user="1603" get_max_reduce_amount="1603" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="19" exp="1795" get_max_from_all_user="1795" get_max_reduce_amount="1795" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="20" exp="1997" get_max_from_all_user="1997" get_max_reduce_amount="1997" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="21" exp="2236" get_max_from_all_user="2236" get_max_reduce_amount="2236" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="22" exp="2469" get_max_from_all_user="2469" get_max_reduce_amount="2469" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="23" exp="2776" get_max_from_all_user="2776" get_max_reduce_amount="2776" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="24" exp="3044" get_max_from_all_user="3044" get_max_reduce_amount="3044" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="25" exp="3293" get_max_from_all_user="3293" get_max_reduce_amount="3293" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="26" exp="3656" get_max_from_all_user="3656" get_max_reduce_amount="3656" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="27" exp="3946" get_max_from_all_user="3946" get_max_reduce_amount="3946" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="28" exp="4289" get_max_from_all_user="4289" get_max_reduce_amount="4289" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="29" exp="4676" get_max_from_all_user="4676" get_max_reduce_amount="4676" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="30" exp="5059" get_max_from_all_user="5059" get_max_reduce_amount="5059" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="31" exp="5474" get_max_from_all_user="5474" get_max_reduce_amount="5474" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="32" exp="5892" get_max_from_all_user="5892" get_max_reduce_amount="5892" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="33" exp="6441" get_max_from_all_user="6441" get_max_reduce_amount="6441" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="34" exp="6876" get_max_from_all_user="6876" get_max_reduce_amount="6876" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="35" exp="7369" get_max_from_all_user="7369" get_max_reduce_amount="7369" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="36" exp="7985" get_max_from_all_user="7985" get_max_reduce_amount="7985" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="37" exp="8467" get_max_from_all_user="8467" get_max_reduce_amount="8467" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="38" exp="9071" get_max_from_all_user="9071" get_max_reduce_amount="9071" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="39" exp="9652" get_max_from_all_user="9652" get_max_reduce_amount="9652" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="40" exp="10276" get_max_from_all_user="10276" get_max_reduce_amount="10276" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="41" exp="10905" get_max_from_all_user="10905" get_max_reduce_amount="10905" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="42" exp="11631" get_max_from_all_user="11631" get_max_reduce_amount="11631" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="43" exp="12374" get_max_from_all_user="12374" get_max_reduce_amount="12374" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="44" exp="13059" get_max_from_all_user="13059" get_max_reduce_amount="13059" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="45" exp="13875" get_max_from_all_user="13875" get_max_reduce_amount="13875" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="46" exp="14770" get_max_from_all_user="14770" get_max_reduce_amount="14770" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="47" exp="15537" get_max_from_all_user="15537" get_max_reduce_amount="15537" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="48" exp="16378" get_max_from_all_user="16378" get_max_reduce_amount="16378" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="49" exp="17312" get_max_from_all_user="17312" get_max_reduce_amount="17312" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="50" exp="18277" get_max_from_all_user="18277" get_max_reduce_amount="18277" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="51" exp="19191" get_max_from_all_user="19191" get_max_reduce_amount="19191" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="52" exp="20151" get_max_from_all_user="20151" get_max_reduce_amount="20151" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="53" exp="21158" get_max_from_all_user="21158" get_max_reduce_amount="21158" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="54" exp="22216" get_max_from_all_user="22216" get_max_reduce_amount="22216" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="55" exp="23327" get_max_from_all_user="23327" get_max_reduce_amount="23327" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="56" exp="24493" get_max_from_all_user="24493" get_max_reduce_amount="24493" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="57" exp="25718" get_max_from_all_user="25718" get_max_reduce_amount="25718" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="58" exp="27004" get_max_from_all_user="27004" get_max_reduce_amount="27004" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="59" exp="28354" get_max_from_all_user="28354" get_max_reduce_amount="28354" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="60" exp="29772" get_max_from_all_user="29772" get_max_reduce_amount="29772" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="61" exp="31260" get_max_from_all_user="31260" get_max_reduce_amount="31260" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="62" exp="32824" get_max_from_all_user="32824" get_max_reduce_amount="32824" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="63" exp="34465" get_max_from_all_user="34465" get_max_reduce_amount="34465" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="64" exp="36188" get_max_from_all_user="36188" get_max_reduce_amount="36188" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="65" exp="37997" get_max_from_all_user="37997" get_max_reduce_amount="37997" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="66" exp="39897" get_max_from_all_user="39897" get_max_reduce_amount="39897" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="67" exp="41892" get_max_from_all_user="41892" get_max_reduce_amount="41892" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="68" exp="43987" get_max_from_all_user="43987" get_max_reduce_amount="43987" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="69" exp="46186" get_max_from_all_user="46186" get_max_reduce_amount="46186" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="70" exp="48495" get_max_from_all_user="48495" get_max_reduce_amount="48495" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="71" exp="50920" get_max_from_all_user="50920" get_max_reduce_amount="50920" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="72" exp="53466" get_max_from_all_user="53466" get_max_reduce_amount="53466" get_max_reduce_interval="60" delay_time="1800"/>
	<level lvl="73" exp="56139" get_max_from_all_user="56139" get_max_reduce_amount="56139" get_max_reduce_interval="60" delay_time="1800"/>
