=== beyond-aion/aion-server/game-server/data/static_data/decomposable_items/decomposable_items.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../items/item_templates.xsd" />
	<xs:element name="decomposable_items">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="decomposable" type="DecomposableItem" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="DecomposableItem">
		<xs:sequence>
			<xs:element name="set" type="DecomposableSet" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="item_id" type="itemId" use="required" />
		<xs:attribute name="selectable" type="xs:boolean" default="false" />
		<xs:attribute name="only_one" type="xs:boolean" default="false" />
		<xs:attribute name="override" type="xs:boolean" default="false" />
	</xs:complexType>
	<xs:complexType name="DecomposableSet">
		<xs:sequence>
			<xs:element name="item" type="DecomposedItem" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="chance" type="xs:float" default="100" />
		<xs:attribute name="min_level" type="xs:int" default="1" />
		<xs:attribute name="max_level" type="xs:int" default="80" />
		<xs:attribute name="race" type="Race" default="PC_ALL" />
		<xs:attribute name="player_classes" type="ListPlayerClass" />
	</xs:complexType>
	<xs:complexType name="DecomposedItem">
		<xs:attribute name="id" type="itemId" use="required" />
		<xs:attribute name="count" type="xs:int" default="1" />
		<xs:attribute name="chance" type="xs:float" default="100" />
	</xs:complexType>
	<xs:simpleType name="ListPlayerClass">
		<xs:list itemType="playerClass" />
	</xs:simpleType>
</xs:schema>

=== beyond-aion/aion-server/game-server/data/static_data/decomposable_items/custom_decomposable_items.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<decomposable_items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="decomposable_items.xsd">
	<decomposable item_id="188050004" override="true"><!-- Red Solorius Stocking -->
		<set>
			<item id="169231091" chance="16.67" /><!-- [Event] Dye: Bright Aqua -->
			<item id="169231092" chance="16.67" /><!-- [Event] Dye: Bright Green -->
			<item id="169231093" chance="16.67" /><!-- [Event] Dye: Bright Sky Blue -->
			<item id="169231094" chance="16.67" /><!-- [Event] Dye: Bright Magenta -->
			<item id="169231095" chance="16.66" /><!-- [Event] Dye: Bright Red -->
			<item id="169231096" chance="16.66" /><!-- [Event] Dye: Bright Blue -->
		</set>
	</decomposable>
	<decomposable item_id="188050007" override="true"><!-- Red Solorius Stocking -->
		<set>
			<item id="169231091" chance="16.67" /><!-- [Event] Dye: Bright Aqua -->
			<item id="169231092" chance="16.67" /><!-- [Event] Dye: Bright Green -->
			<item id="169231093" chance="16.67" /><!-- [Event] Dye: Bright Sky Blue -->
			<item id="169231094" chance="16.67" /><!-- [Event] Dye: Bright Magenta -->
			<item id="169231095" chance="16.66" /><!-- [Event] Dye: Bright Red -->
			<item id="169231096" chance="16.66" /><!-- [Event] Dye: Bright Blue -->
		</set>
	</decomposable>
	<decomposable item_id="188050702" override="true"><!-- Veille's 1st Grade Reward -->
		<set>
			<item id="182006281" count="3" /><!-- Veille's Favor -->
		</set>
		<set>
			<item id="186000242" count="5" /><!-- Ceramium Medal -->
		</set>
		<set chance="7">
			<item id="169610112" /><!-- [Title] Vanquisher of Mastarius -->
		</set>
		<set chance="2">
			<item id="168000161" chance="5.88" /><!-- Illusion Godstone: Meslamtaeda's Greed -->
			<item id="168000162" chance="5.88" /><!-- Illusion Godstone: Ereshkigal's Honor -->
			<item id="168000163" chance="5.88" /><!-- Illusion Godstone: Nezekan's Advance -->
			<item id="168000164" chance="5.88" /><!-- Illusion Godstone: Beritra's Plot -->
			<item id="168000165" chance="5.88" /><!-- Illusion Godstone: Fregion's Trick -->
			<item id="168000166" chance="5.88" /><!-- Illusion Godstone: Lumiel's Intervention -->
			<item id="168000167" chance="5.88" /><!-- Illusion Godstone: Kaisinel's Fantasy -->
			<item id="168000168" chance="5.88" /><!-- Illusion Godstone: Zikel's Arrogance -->
			<item id="168000169" chance="5.88" /><!-- Illusion Godstone: Fregion's Stratagem -->
			<item id="168000170" chance="5.88" /><!-- Illusion Godstone: Tiamat's Counterattack -->
			<item id="168000171" chance="5.88" /><!-- Illusion Godstone: Marchutan's Impartiality -->
			<item id="168000172" chance="5.88" /><!-- Illusion Godstone: Yustiel's Generosity -->
			<item id="168000173" chance="5.89" /><!-- Illusion Godstone: Beritra's Selfishness -->
			<item id="168000174" chance="5.88" /><!-- Illusion Godstone: Tiamat's Fury -->
			<item id="168000175" chance="5.89" /><!-- Illusion Godstone: Triniel's Rationality -->
			<item id="168000176" chance="5.89" /><!-- Illusion Godstone: Vaizel's Vow -->
			<item id="168000177" chance="5.89" /><!-- Illusion Godstone: Meslamtaeda's Regret -->
		</set>
	</decomposable>
	<decomposable item_id="188050703" override="true"><!-- Veille's 2nd Grade Reward -->
		<set>
			<item id="182006281" count="2" /><!-- Veille's Favor -->
		</set>
		<set>
			<item id="186000242" count="3" /><!-- Ceramium Medal -->
		</set>
		<set chance="6">
			<item id="169610112" /><!-- [Title] Vanquisher of Mastarius -->
		</set>
		<set chance="1.5">
			<item id="168000161" chance="5.88" /><!-- Illusion Godstone: Meslamtaeda's Greed -->
			<item id="168000162" chance="5.88" /><!-- Illusion Godstone: Ereshkigal's Honor -->
			<item id="168000163" chance="5.88" /><!-- Illusion Godstone: Nezekan's Advance -->
			<item id="168000164" chance="5.88" /><!-- Illusion Godstone: Beritra's Plot -->
			<item id="168000165" chance="5.88" /><!-- Illusion Godstone: Fregion's Trick -->
			<item id="168000166" chance="5.88" /><!-- Illusion Godstone: Lumiel's Intervention -->
			<item id="168000167" chance="5.88" /><!-- Illusion Godstone: Kaisinel's Fantasy -->
			<item id="168000168" chance="5.88" /><!-- Illusion Godstone: Zikel's Arrogance -->
			<item id="168000169" chance="5.88" /><!-- Illusion Godstone: Fregion's Stratagem -->
			<item id="168000170" chance="5.88" /><!-- Illusion Godstone: Tiamat's Counterattack -->
			<item id="168000171" chance="5.88" /><!-- Illusion Godstone: Marchutan's Impartiality -->
			<item id="168000172" chance="5.88" /><!-- Illusion Godstone: Yustiel's Generosity -->
			<item id="168000173" chance="5.89" /><!-- Illusion Godstone: Beritra's Selfishness -->
			<item id="168000174" chance="5.88" /><!-- Illusion Godstone: Tiamat's Fury -->
			<item id="168000175" chance="5.89" /><!-- Illusion Godstone: Triniel's Rationality -->
			<item id="168000176" chance="5.89" /><!-- Illusion Godstone: Vaizel's Vow -->
			<item id="168000177" chance="5.89" /><!-- Illusion Godstone: Meslamtaeda's Regret -->
		</set>
	</decomposable>
	<decomposable item_id="188050704" override="true"><!-- Veille's 3rd Grade Reward -->
		<set>
			<item id="182006281" /><!-- Veille's Favor -->
		</set>
		<set>
			<item id="186000242" count="2" /><!-- Ceramium Medal -->
		</set>
		<set chance="5">
			<item id="169610112" /><!-- [Title] Vanquisher of Mastarius -->
		</set>
		<set chance="1">
			<item id="168000161" chance="5.88" /><!-- Illusion Godstone: Meslamtaeda's Greed -->
			<item id="168000162" chance="5.88" /><!-- Illusion Godstone: Ereshkigal's Honor -->
			<item id="168000163" chance="5.88" /><!-- Illusion Godstone: Nezekan's Advance -->
			<item id="168000164" chance="5.88" /><!-- Illusion Godstone: Beritra's Plot -->
			<item id="168000165" chance="5.88" /><!-- Illusion Godstone: Fregion's Trick -->
			<item id="168000166" chance="5.88" /><!-- Illusion Godstone: Lumiel's Intervention -->
			<item id="168000167" chance="5.88" /><!-- Illusion Godstone: Kaisinel's Fantasy -->
			<item id="168000168" chance="5.88" /><!-- Illusion Godstone: Zikel's Arrogance -->
			<item id="168000169" chance="5.88" /><!-- Illusion Godstone: Fregion's Stratagem -->
			<item id="168000170" chance="5.88" /><!-- Illusion Godstone: Tiamat's Counterattack -->
			<item id="168000171" chance="5.88" /><!-- Illusion Godstone: Marchutan's Impartiality -->
			<item id="168000172" chance="5.88" /><!-- Illusion Godstone: Yustiel's Generosity -->
			<item id="168000173" chance="5.89" /><!-- Illusion Godstone: Beritra's Selfishness -->
			<item id="168000174" chance="5.88" /><!-- Illusion Godstone: Tiamat's Fury -->
			<item id="168000175" chance="5.89" /><!-- Illusion Godstone: Triniel's Rationality -->
			<item id="168000176" chance="5.89" /><!-- Illusion Godstone: Vaizel's Vow -->
			<item id="168000177" chance="5.89" /><!-- Illusion Godstone: Meslamtaeda's Regret -->
		</set>
	</decomposable>
	<decomposable item_id="188050706" override="true"><!-- Mastarius' 1st Grade Reward -->
		<set>
			<item id="182006282" count="3" /><!-- Mastarius' Favor -->
		</set>
		<set>
			<item id="186000242" count="5" /><!-- Ceramium Medal -->
		</set>
		<set chance="7">
			<item id="169610312" /><!-- [Title] Vanquisher of Veille -->
		</set>
		<set chance="2">
			<item id="168000161" chance="5.88" /><!-- Illusion Godstone: Meslamtaeda's Greed -->
			<item id="168000162" chance="5.88" /><!-- Illusion Godstone: Ereshkigal's Honor -->
			<item id="168000163" chance="5.88" /><!-- Illusion Godstone: Nezekan's Advance -->
			<item id="168000164" chance="5.88" /><!-- Illusion Godstone: Beritra's Plot -->
			<item id="168000165" chance="5.88" /><!-- Illusion Godstone: Fregion's Trick -->
			<item id="168000166" chance="5.88" /><!-- Illusion Godstone: Lumiel's Intervention -->
			<item id="168000167" chance="5.88" /><!-- Illusion Godstone: Kaisinel's Fantasy -->
			<item id="168000168" chance="5.88" /><!-- Illusion Godstone: Zikel's Arrogance -->
			<item id="168000169" chance="5.88" /><!-- Illusion Godstone: Fregion's Stratagem -->
			<item id="168000170" chance="5.88" /><!-- Illusion Godstone: Tiamat's Counterattack -->
			<item id="168000171" chance="5.88" /><!-- Illusion Godstone: Marchutan's Impartiality -->
			<item id="168000172" chance="5.88" /><!-- Illusion Godstone: Yustiel's Generosity -->
			<item id="168000173" chance="5.89" /><!-- Illusion Godstone: Beritra's Selfishness -->
			<item id="168000174" chance="5.88" /><!-- Illusion Godstone: Tiamat's Fury -->
			<item id="168000175" chance="5.89" /><!-- Illusion Godstone: Triniel's Rationality -->
			<item id="168000176" chance="5.89" /><!-- Illusion Godstone: Vaizel's Vow -->
			<item id="168000177" chance="5.89" /><!-- Illusion Godstone: Meslamtaeda's Regret -->
		</set>
	</decomposable>
	<decomposable item_id="188050707" override="true"><!-- Mastarius' 2nd Grade Reward -->
		<set>
			<item id="182006282" count="2" /><!-- Mastarius' Favor -->
		</set>
		<set>
			<item id="186000242" count="3" /><!-- Ceramium Medal -->
		</set>
		<set chance="6">
			<item id="169610312" /><!-- [Title] Vanquisher of Veille -->
		</set>
		<set chance="1.5">
			<item id="168000161" chance="5.88" /><!-- Illusion Godstone: Meslamtaeda's Greed -->
			<item id="168000162" chance="5.88" /><!-- Illusion Godstone: Ereshkigal's Honor -->
			<item id="168000163" chance="5.88" /><!-- Illusion Godstone: Nezekan's Advance -->
			<item id="168000164" chance="5.88" /><!-- Illusion Godstone: Beritra's Plot -->
			<item id="168000165" chance="5.88" /><!-- Illusion Godstone: Fregion's Trick -->
			<item id="168000166" chance="5.88" /><!-- Illusion Godstone: Lumiel's Intervention -->
			<item id="168000167" chance="5.88" /><!-- Illusion Godstone: Kaisinel's Fantasy -->
			<item id="168000168" chance="5.88" /><!-- Illusion Godstone: Zikel's Arrogance -->
			<item id="168000169" chance="5.88" /><!-- Illusion Godstone: Fregion's Stratagem -->
