=== beyond-aion/aion-server/game-server/data/static_data/spawns/spawns.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../global_types.xsd" />
	<xs:include schemaLocation="../import.xsd" />
	<xs:element name="spawns" type="SpawnsData" />

	<xs:complexType name="SpawnsData">
		<xs:sequence>
			<xs:element ref="import" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="spawn_map" type="SpawnMap" minOccurs="0" maxOccurs="unbounded">
				<xs:unique name="unique-npc-id"><!-- a spawn entry must be unique per npc_id (see SpawnData#afterUnmarshal) -->
					<!-- entry with same npc_id may appear twice if one has custom="true" -->
					<xs:selector xpath="spawn" />
					<xs:field xpath="@npc_id" />
					<xs:field xpath="@custom" />
				</xs:unique>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SpawnMap">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="base_spawn" type="BaseSpawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="rift_spawn" type="RiftSpawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="siege_spawn" type="SiegeSpawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="vortex_spawn" type="VortexSpawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="mercenary_spawn" type="MercenarySpawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="ahserion_spawn" type="AhserionsFlightSpawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="map_id" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="BaseSpawn">
		<xs:sequence>
			<xs:element name="simple_race" type="SimpleRaceTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int"/>
		<xs:attribute name="world" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="SimpleRaceTemplate">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="race" type="Race" use="required" />
	</xs:complexType>
	<xs:complexType name="RiftSpawn">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int"/>
		<xs:attribute name="world" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="VortexSpawn">
		<xs:sequence>
			<xs:element name="state_type" type="VortexStateTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="VortexStateTemplate">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="state" type="StateType"/>
	</xs:complexType>
	<xs:complexType name="AhserionsFlightSpawn">
		<xs:sequence>
			<xs:element name="ahserion_stage_spawn" type="AhserionStageSpawnTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="faction" type="PanesterraFaction"/>
	</xs:complexType>
	<xs:complexType name="AhserionStageSpawnTemplate">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="stage" type="xs:int"/>
	</xs:complexType>
	<xs:simpleType name="PanesterraFaction">
		<xs:restriction base="xs:string">
			<xs:enumeration value="BELUS"/>
			<xs:enumeration value="ASPIDA"/>
			<xs:enumeration value="ATANATOS"/>
			<xs:enumeration value="DISILLON"/>
			<xs:enumeration value="BALAUR"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="StateType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="INVASION"/>
			<xs:enumeration value="PEACE"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="SiegeSpawn">
		<xs:sequence>
			<xs:element name="siege_race" type="SiegeRaceTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="siege_id" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="SiegeRaceTemplate">
		<xs:sequence>
			<xs:element name="siege_mod" type="SiegeModTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="race" type="SiegeRaceType"/>
	</xs:complexType>
	<xs:complexType name="SiegeModTemplate">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="mod" type="SiegeModType"/>
	</xs:complexType>
	<xs:complexType name="MercenarySpawn">		
		<xs:sequence>
			<xs:element name="mercenary_race" type="MercenaryRace" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="siege_id" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="MercenaryRace">		
		<xs:sequence>
			<xs:element name="mercenary_zone" type="MercenaryZone" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="race" type="Race"/>
	</xs:complexType>
	<xs:complexType name="MercenaryZone">		
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="zone" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="Spawn">
		<xs:sequence>
			<xs:element name="temporary_spawn" type="TemporarySpawn" minOccurs="0" maxOccurs="1"/>
			<xs:element name="spot" type="SpawnSpotTemplate" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="npc_id" type="xs:int" use="required"/>
		<xs:attribute name="pool" type="xs:int" use="optional"/>
		<xs:attribute name="respawn_time" type="xs:int"/>
		<xs:attribute name="handler" type="SpawnHandlerType"/>
		<xs:attribute name="custom" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="difficult_id" type="xs:byte"/>
	</xs:complexType>
	<xs:complexType name="SpawnSpotTemplate">
		<xs:sequence>
			<xs:element name="temporary_spawn" type="TemporarySpawn" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="x" type="xs:float"/>
		<xs:attribute name="y" type="xs:float"/>
		<xs:attribute name="z" type="xs:float"/>
		<xs:attribute name="h" type="HeadingType" use="optional" default="0"/>
		<xs:attribute name="static_id" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="random_walk" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="walker_id" type="xs:string"/>
		<xs:attribute name="walker_index" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="fly" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="anchor" type="xs:string"/>
		<xs:attribute name="state" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="ai" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="TemporarySpawn">
		<xs:attribute name="weekdays" type="WeekdayList"/>
		<xs:attribute name="spawn_time" type="xs:string"/>
		<xs:attribute name="despawn_time" type="xs:string"/>
	</xs:complexType>
	<xs:simpleType name="WeekdayList">
		<xs:list itemType="Weekday" />
	</xs:simpleType>
	<xs:simpleType name="Weekday">
		<xs:restriction base="xs:string">
			<xs:enumeration value="MONDAY"/>
			<xs:enumeration value="TUESDAY"/>
			<xs:enumeration value="WEDNESDAY"/>
			<xs:enumeration value="THURSDAY"/>
			<xs:enumeration value="FRIDAY"/>
			<xs:enumeration value="SATURDAY"/>
			<xs:enumeration value="SUNDAY"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SiegeModType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="PEACE"/>
			<xs:enumeration value="SIEGE"/>
			<xs:enumeration value="LANDING"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="HeadingType">
		<xs:restriction base="xs:byte">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="120"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SiegeRaceType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ELYOS"/>
			<xs:enumeration value="ASMODIANS"/>
			<xs:enumeration value="BALAUR"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SpawnHandlerType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ATTACKER"/>
			<xs:enumeration value="BOSS"/>
			<xs:enumeration value="FLAG"/>
			<xs:enumeration value="GUARDIAN"/>
			<xs:enumeration value="MERCHANT"/>			
			<xs:enumeration value="OUTRIDER"/>
			<xs:enumeration value="OUTRIDER_ENHANCED"/>
			<xs:enumeration value="RIFT"/>
			<xs:enumeration value="SENTINEL"/>
			<xs:enumeration value="STATIC"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== beyond-aion/aion-server/game-server/data/static_data/spawns/Instances/300360000_Arena_of_Discipline.xml
<?xml version="1.0" encoding="utf-8"?>
<spawns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../spawns.xsd">
	<spawn_map map_id="300360000">
		<!-- Blessed Relics -->
		<spawn npc_id="701216" respawn_time="105" difficult_id="1">
			<spot x="692.663" y="1770.740" z="219.014"/>
			<spot x="707.409" y="1779.437" z="165.419"/>
		</spawn>
		<!-- Blessed Relics -->
		<spawn npc_id="701221" respawn_time="105" difficult_id="2">
			<spot x="692.663" y="1770.740" z="219.014" state="2"/>
			<spot x="707.409" y="1779.437" z="165.419" state="2"/>
		</spawn>
		<!-- Blessed Relics -->
		<spawn npc_id="701226" respawn_time="105" difficult_id="3">
			<spot x="692.663" y="1770.740" z="219.014"/>
			<spot x="707.409" y="1779.437" z="165.419"/>
		</spawn>
		<!-- Blessed Relics -->
		<spawn npc_id="701215" respawn_time="105" difficult_id="1">
			<spot x="1848.173" y="1737.195" z="305.182"/>
		</spawn>
		<!-- Blessed Relics -->
		<spawn npc_id="701220" respawn_time="105" difficult_id="2">
			<spot x="1848.173" y="1737.195" z="305.182"/>
		</spawn>
		<!-- Blessed Relics -->
		<spawn npc_id="701225" respawn_time="105" difficult_id="3">
			<spot x="1848.173" y="1737.195" z="305.182"/>
		</spawn>
		<!-- Crater -->
		<spawn npc_id="701219" respawn_time="30" difficult_id="1">
			<spot x="676.005" y="1766.244" z="171.897"/>
			<spot x="680.167" y="1767.332" z="164.170"/>
			<spot x="682.348" y="1780.562" z="164.022"/>
			<spot x="682.538" y="1762.745" z="164.170"/>
			<spot x="691.514" y="1760.514" z="164.170"/>
			<spot x="693.787" y="1780.437" z="163.861"/>
			<spot x="695.261" y="1765.080" z="164.170"/>
			<spot x="697.315" y="1777.487" z="163.861"/>
			<spot x="700.407" y="1756.772" z="177.998"/>
			<spot x="701.967" y="1765.882" z="164.438"/>
			<spot x="703.459" y="1775.125" z="164.438"/>
			<spot x="706.059" y="1761.232" z="163.933"/>
			<spot x="707.120" y="1768.369" z="164.189"/>
			<spot x="711.216" y="1772.974" z="164.674"/>
		</spawn>
		<!-- Crater -->
		<spawn npc_id="701224" respawn_time="30" difficult_id="2">
			<spot x="676.005" y="1766.244" z="171.897" state="2"/>
			<spot x="680.167" y="1767.332" z="164.170" state="2"/>
			<spot x="682.348" y="1780.562" z="164.022" state="2"/>
			<spot x="682.538" y="1762.745" z="164.170" state="2"/>
			<spot x="691.514" y="1760.514" z="164.170" state="2"/>
			<spot x="693.787" y="1780.437" z="163.861" state="2"/>
			<spot x="695.261" y="1765.080" z="164.170" state="2"/>
			<spot x="697.315" y="1777.487" z="163.861" state="2"/>
			<spot x="700.407" y="1756.772" z="177.998" state="2"/>
			<spot x="701.967" y="1765.882" z="164.438" state="2"/>
			<spot x="703.459" y="1775.125" z="164.438" state="2"/>
			<spot x="706.059" y="1761.232" z="163.933" state="2"/>
			<spot x="707.120" y="1768.369" z="164.189" state="2"/>
			<spot x="711.216" y="1772.974" z="164.674" state="2"/>
		</spawn>
		<!-- Crater -->
		<spawn npc_id="701229" respawn_time="30" difficult_id="3">
			<spot x="676.005" y="1766.244" z="171.897"/>
			<spot x="680.167" y="1767.332" z="164.170"/>
			<spot x="682.348" y="1780.562" z="164.022"/>
			<spot x="682.538" y="1762.745" z="164.170"/>
			<spot x="691.514" y="1760.514" z="164.170"/>
			<spot x="693.787" y="1780.437" z="163.861"/>
			<spot x="695.261" y="1765.080" z="164.170"/>
			<spot x="697.315" y="1777.487" z="163.861"/>
			<spot x="700.407" y="1756.772" z="177.998"/>
			<spot x="701.967" y="1765.882" z="164.438"/>
			<spot x="703.459" y="1775.125" z="164.438"/>
			<spot x="706.059" y="1761.232" z="163.933"/>
			<spot x="707.120" y="1768.369" z="164.189"/>
			<spot x="711.216" y="1772.974" z="164.674"/>
		</spawn>
		<!-- Lava Floor -->
		<spawn npc_id="701218" respawn_time="30" difficult_id="1">
			<spot x="687.888" y="1766.859" z="163.000"/>
			<spot x="688.366" y="1777.590" z="163.000"/>
			<spot x="699.176" y="1772.244" z="163.000"/>
			<spot x="707.605" y="1779.565" z="163.673"/>
		</spawn>
		<!-- Lava Floor -->
		<spawn npc_id="701223" respawn_time="30" difficult_id="2">
			<spot x="687.888" y="1766.859" z="163.000"/>
			<spot x="688.366" y="1777.590" z="163.000"/>
			<spot x="699.176" y="1772.244" z="163.000"/>
			<spot x="707.605" y="1779.565" z="163.673"/>
		</spawn>
		<!-- Lava Floor -->
		<spawn npc_id="701228" respawn_time="30" difficult_id="3">
			<spot x="687.888" y="1766.859" z="163.000"/>
			<spot x="688.366" y="1777.590" z="163.000"/>
			<spot x="699.176" y="1772.244" z="163.000"/>
			<spot x="707.605" y="1779.565" z="163.673"/>
		</spawn>
		<!-- Red Sand Tog -->
		<spawn npc_id="218693" respawn_time="105" difficult_id="1">
			<spot x="1856.197" y="1071.305" z="337.287" h="90"/>
		</spawn>
		<!-- Red Sand Tog -->
		<spawn npc_id="218706" respawn_time="105" difficult_id="2">
			<spot x="1856.197" y="1071.305" z="337.287" h="90"/>
		</spawn>
		<!-- Red Sand Tog -->
		<spawn npc_id="218719" respawn_time="105" difficult_id="3">
			<spot x="1856.197" y="1071.305" z="337.287" h="90"/>
		</spawn>
		<!-- Red Sand Tog -->
		<spawn npc_id="233058" respawn_time="105" difficult_id="4">
			<spot x="1856.197" y="1071.305" z="337.287" h="90"/>
		</spawn>
		<!-- Tog Manger -->
		<spawn npc_id="218757" respawn_time="105">
			<spot x="1853.310" y="1072.531" z="337.734"/>
		</spawn>
		<!-- Treasure Box -->
		<spawn npc_id="218802" respawn_time="105">
			<spot x="297.641" y="1239.489" z="267.572"/>
		</spawn>
	</spawn_map>
</spawns>

=== beyond-aion/aion-server/game-server/data/static_data/spawns/Npcs/Custom/Skill_CD_Reset_Shugo.xml
<?xml version="1.0" encoding="utf-8"?>
<spawns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../spawns.xsd">
	<!-- Sanctum Arena -->
	<spawn_map map_id="110010000">
		<spawn npc_id="833543" respawn_time="295">
			<spot x="1422.7744" y="1250.0612" z="569.47" h="16" ai="customcdreset" />
		</spawn>
	</spawn_map>
	<!-- Pandaemonium Arena -->
	<spawn_map map_id="120010000">
		<spawn npc_id="833543" respawn_time="295">
			<spot x="930.0757" y="1604.4641" z="225.6" h="105" ai="customcdreset" />
		</spawn>
	</spawn_map>
	<!-- Discipline Training Grounds -->
	<spawn_map map_id="300430000">
		<spawn npc_id="833543" respawn_time="295">
			<!-- The Plaza of Struggle -->
			<spot x="1831.303" y="1719.6138" z="305.14697" h="15" ai="customcdreset" />
			<!-- Red Sand Arena -->
			<spot x="1856.4928" y="1075.8822" z="338.22055" h="87" ai="customcdreset" />
			<!-- Abyss Bridge -->
			<spot x="294.2966" y="1245.7626" z="268.07672" h="54" ai="customcdreset" />
			<!-- Collapsed Wind Tower -->
			<spot x="685.91534" y="1776.664" z="188.9151" h="51" ai="customcdreset" />
		</spawn>
	</spawn_map>
</spawns>

=== beyond-aion/aion-server/game-server/data/static_data/spawns/Npcs/Custom/Morph_Recipe_Merchants.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<spawns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../spawns.xsd">
	<!-- Sanctum -->
	<spawn_map map_id="110010000">
		<!-- Raphia -->
		<spawn npc_id="832773" respawn_time="295">
			<spot x="1887.0967" y="1526.392" z="590.1345" h="60" />
		</spawn>
		<!-- Distine -->
		<spawn npc_id="799060" respawn_time="295">
			<spot x="1887.0967" y="1524.9606" z="590.1345" h="60" />
		</spawn>
	</spawn_map>
	<!-- Pandaemonium -->
	<spawn_map map_id="120010000">
		<!-- Roianan -->
		<spawn npc_id="832787" respawn_time="295">
			<spot x="1186.7118" y="1551.3257" z="213.96336" h="6" />
		</spawn>
		<!-- Eistin -->
		<spawn npc_id="799373" respawn_time="295">
			<spot x="1186.2657" y="1552.545" z="213.96336" h="6" />
		</spawn>
	</spawn_map>
</spawns>

=== beyond-aion/aion-server/game-server/data/static_data/spawns/Instances/310010000_Karamatis.xml
<?xml version="1.0" encoding="utf-8"?>
<spawns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../spawns.xsd">
	<spawn_map map_id="310010000">
		<!-- Archon Legionary -->
		<spawn npc_id="205010">
			<spot x="109.0000" y="208.0000" z="213.0000" h="93" state="35"/>
			<spot x="143.0000" y="232.0000" z="199.0000" h="50" state="35"/>
			<spot x="152.0000" y="224.0000" z="213.0000" h="70" state="35"/>
			<spot x="185.0000" y="236.0000" z="223.0000" h="30" state="35"/>
			<spot x="188.1988" y="203.8012" z="219.0000" h="105" state="35"/>
		</spawn>
		<!-- Archon Legionary -->
		<spawn npc_id="205009">
			<spot x="127.0000" y="203.0000" z="225.0000" h="30" state="35"/>
			<spot x="164.0000" y="221.0000" z="220.0000" h="76" state="35"/>
			<spot x="164.0000" y="239.0000" z="220.0000" h="51" state="35"/>
			<spot x="166.0000" y="190.0000" z="203.0000" h="70" state="35"/>
			<spot x="175.0000" y="268.0000" z="212.0000" h="69" state="35"/>
		</spawn>
		<!-- Belpartan -->
		<spawn npc_id="205000">
			<spot x="85.0000" y="191.0000" z="231.6508" h="66"/>
		</spawn>
		<!-- Centurion -->
		<spawn npc_id="205011">
			<spot x="117.8750" y="214.2500" z="222.1000" h="106" state="35"/>
			<spot x="130.9070" y="204.4535" z="223.0453" h="9" state="35"/>
		</spawn>
		<!-- Centurion -->
		<spawn npc_id="205013">
			<spot x="159.3518" y="223.8024" z="218.5506" h="79" state="35"/>
			<spot x="173.2500" y="233.5000" z="226.1000" h="79" state="35"/>
		</spawn>
		<!-- Grunt -->
		<spawn npc_id="211044">
			<spot x="222.2201" y="283.6205" z="206.6727" h="101"/>
			<spot x="245.9583" y="289.8067" z="206.9398" h="98"/>
			<spot x="254.0000" y="300.0000" z="206.7753" h="30"/>
			<spot x="256.0000" y="303.0000" z="205.9827" h="60"/>
			<spot x="258.1224" y="241.2517" z="209.8867" h="49"/>
			<spot x="264.1305" y="210.4966" z="205.7615" h="49"/>
			<spot x="275.1180" y="299.2916" z="205.8489" h="98"/>
			<spot x="285.0000" y="229.0000" z="209.3622" h="15"/>
			<spot x="288.0000" y="229.0000" z="209.3701" h="38"/>
			<spot x="296.0000" y="276.0000" z="206.3569" h="21"/>
			<spot x="299.0000" y="276.0000" z="206.4478" h="45"/>
			<spot x="302.0000" y="259.0000" z="205.2299" h="24"/>
		</spawn>
		<!-- Legionary -->
		<spawn npc_id="205001">
			<spot x="63.5000" y="183.7500" z="228.7197" h="86"/>
		</spawn>
		<!-- Legionary -->
		<spawn npc_id="205019">
			<spot x="61.7500" y="176.3750" z="228.9820" h="58"/>
			<spot x="67.5000" y="185.7500" z="228.4363" h="81"/>
		</spawn>
		<!-- Legionary -->
		<spawn npc_id="205018">
			<spot x="59.5000" y="181.7500" z="228.7547" h="80"/>
			<spot x="65.7500" y="179.3750" z="228.8462" h="56"/>
		</spawn>
		<!-- Legionary -->
		<spawn npc_id="205002">
			<spot x="69.7500" y="181.3750" z="228.4128" h="70"/>
		</spawn>
		<!-- Legionary -->
		<spawn npc_id="205012">
			<spot x="117.0778" y="216.1102" z="222.1000" h="97" state="35"/>
			<spot x="127.0425" y="202.9621" z="223.0000" h="18" state="35"/>
		</spawn>
		<!-- Legionary -->
		<spawn npc_id="205007">
			<spot x="110.0000" y="206.0000" z="213.0000" h="33" state="35"/>
			<spot x="126.0000" y="205.0000" z="225.0000" h="90" state="35"/>
			<spot x="162.0000" y="219.0000" z="220.0000" h="15" state="35"/>
			<spot x="164.0000" y="188.0000" z="203.0000" h="11" state="35"/>
			<spot x="185.0000" y="238.0000" z="223.0000" h="90" state="35"/>
			<spot x="190.0000" y="202.0000" z="219.0000" h="45" state="35"/>
		</spawn>
		<!-- Legionary -->
		<spawn npc_id="205008">
			<spot x="141.0000" y="234.0000" z="199.0000" h="100" state="35"/>
			<spot x="150.0000" y="222.0000" z="213.0000" h="11" state="35"/>
			<spot x="162.0000" y="240.0000" z="220.0000" h="111" state="35"/>
			<spot x="173.0000" y="267.0000" z="212.0000" h="8" state="35"/>
		</spawn>
		<!-- Legionary -->
		<spawn npc_id="205014">
			<spot x="161.3263" y="224.7709" z="218.5592" h="79" state="35"/>
			<spot x="175.1441" y="234.6884" z="226.1000" h="79" state="35"/>
		</spawn>
		<!-- Legionary -->
		<spawn npc_id="205015">
			<spot x="204.0000" y="255.9870" z="216.1000" h="91" state="35"/>
		</spawn>
		<!-- Legionary -->
		<spawn npc_id="205016">
			<spot x="254.0000" y="303.0000" z="205.5542" h="90"/>
			<spot x="287.0000" y="231.0000" z="209.6033" h="75"/>
		</spawn>
		<!-- Legionary -->
		<spawn npc_id="205017">
			<spot x="297.0000" y="278.0000" z="206.6896" h="105"/>
		</spawn>
	</spawn_map>
</spawns>

=== beyond-aion/aion-server/game-server/data/static_data/spawns/Bases/210020000_Eltnen.xml
<?xml version="1.0" encoding="UTF-8"?>
<spawns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../spawns.xsd">
	<spawn_map map_id="210020000">
		<base_spawn id="2120"> <!-- Kaidan Watchpost -->
			<simple_race race="ELYOS">
				<!-- Elyos Territory -->
				<spawn npc_id="701799" handler="FLAG">
					<spot x="1811.875" y="1101.75" z="435.2568" h="15"/>
				</spawn>
				<!-- Territory Boss -->
				<spawn npc_id="231553" handler="BOSS">
					<spot x="1817.8046" y="1106" z="435.60056" h="0"/>
				</spawn>
				<!-- Elyos Eltnen Inspector (possible for Quest?) -->
				<spawn npc_id="231616" handler="ATTACKER">
					<spot x="1840.2500" y="1064.8750" z="432.3223" h="60"/>
				</spawn>
				<!-- Eltnen Defender -->
				<spawn npc_id="232062" handler="SENTINEL" respawn_time="295">
					<spot x="1800.5" y="1107.5" z="436.125" h="15"/>
					<spot x="1831.75" y="1090.875" z="435.75" h="105"/>
					<spot x="1798.75" y="1120.0" z="432.6875" h="45"/>
					<spot x="1823.5" y="1085.125" z="431.7520" h="90"/>
				</spawn>
				<!-- Alcman Administration Officer -->
				<spawn npc_id="801164" handler="MERCHANT" respawn_time="295">
					<spot x="1821.25" y="1102.75" z="436.375" h="67"/>
				</spawn>
				<!-- Apion Warehouse Manager -->
				<spawn npc_id="801163" handler="MERCHANT" respawn_time="295">
					<spot x="1801.875" y="1098.125" z="436.375" h="15"/>
				</spawn>
				<!-- Aelius General Goods Merchant -->
				<spawn npc_id="801162" handler="MERCHANT" respawn_time="295">
					<spot x="1801.5" y="1104.25" z="436.375"/>
				</spawn>
			</simple_race>
			<simple_race race="ASMODIANS">
				<!-- Asmodian Territory -->
				<spawn npc_id="701800" handler="FLAG">
					<spot x="1811.875" y="1101.75" z="435.2568" h="15"/>
				</spawn>
				<!-- Territory Boss -->
				<spawn npc_id="231554" handler="BOSS">
					<spot x="1817.8046" y="1106" z="435.60056" h="0"/>
				</spawn>
				<!-- Asmodian Eltnen Inspector (possible for Quest?) -->
				<spawn npc_id="231617" handler="ATTACKER">
					<spot x="1840.2500" y="1064.8750" z="432.3223" h="60"/>
				</spawn>
				<!-- Eltnen Infiltrator -->
				<spawn npc_id="232065" handler="SENTINEL" respawn_time="295">
					<spot x="1798.75" y="1120" z="432.6875" h="45"/>
					<spot x="1800.5" y="1107.5" z="436.125" h="15"/>
					<spot x="1823.5" y="1085.125" z="431.7520" h="90"/>
					<spot x="1831.75" y="1090.875" z="435.75" h="105"/>
				</spawn>
				<!-- Dalla Administration Officer -->
				<spawn npc_id="801167" handler="MERCHANT" respawn_time="295">
					<spot x="1821.25" y="1102.75" z="436.375" h="67"/>
				</spawn>
				<!-- Thorgil Warehouse Manager -->
				<spawn npc_id="801166" handler="MERCHANT" respawn_time="295">
					<spot x="1801.875" y="1098.125" z="436.375" h="15"/>
				</spawn>
				<!-- Hrothgar General Goods Merchant -->
				<spawn npc_id="801165" handler="MERCHANT" respawn_time="295">
					<spot x="1801.5" y="1104.25" z="436.375"/>
				</spawn>
			</simple_race>
			<simple_race race="NPC">
				<!-- Krall Territory -->
				<spawn npc_id="701797" handler="FLAG">
					<spot x="1811.875" y="1101.75" z="435.2568" h="15"/>
				</spawn>
				<!-- Territory Boss -->
				<spawn npc_id="231552" handler="BOSS">
					<spot x="1817.8046" y="1106" z="435.60056"/>
				</spawn>
				<!-- Kaidan Assassin -->
				<spawn npc_id="231607" handler="ATTACKER">
					<spot x="1816.6250" y="1106.2500" z="435.5107"/>
				</spawn>
				<!-- Kaidan Vanguard (Shieldcaptain) -->
				<spawn npc_id="231599" handler="SENTINEL" respawn_time="295">
					<spot x="1840.2500" y="1064.8750" z="432.3223" h="60"/>
				</spawn>
				<!-- Kaidan Protector -->
				<spawn npc_id="231579" handler="SENTINEL" respawn_time="295">
					<spot x="1823.5" y="1085.125" z="431.7520" h="90"/>
					<spot x="1800.5" y="1107.5" z="434.7188" h="15"/>
					<spot x="1831.75" y="1090.875" z="433.9434" h="105"/>
					<spot x="1798.75" y="1120" z="432.6875" h="45"/>
				</spawn>
			</simple_race>
		  </base_spawn>
		<base_spawn id="2121"> <!-- Eracus Outpost -->
			<simple_race race="ELYOS">
				<!-- Elyos Territory -->
				<spawn npc_id="701799" handler="FLAG">
					<spot x="1010.0192" y="664.5961" z="309.7885" h="30"/>
				</spawn>
				<!-- Territory Boss -->
				<spawn npc_id="231550" handler="BOSS">
					<spot x="1015.625" y="661.875" z="309.99072" h="60"/>
				</spawn>
				<!-- Elyos Eltnen Inspector (possible for Quest?) -->
				<spawn npc_id="231614" handler="ATTACKER">
					<spot x="982.7500" y="701.0000" z="302.3125" h="105"/>
				</spawn>
				<!-- Eltnen Sentinel -->
				<spawn npc_id="231581" handler="SENTINEL" respawn_time="295">
					<spot x="1000.375" y="663.625" z="307.3246" h="60"/>
					<spot x="1000.875" y="668.125" z="307.3246" h="60"/>
					<spot x="1012.8298" y="676.36615" z="306.99368" h="30"/>
					<spot x="1017.625" y="674.875" z="306.99368" h="30"/>
				</spawn>
				<!-- Akron General Goods -->
				<spawn npc_id="801156" handler="MERCHANT" respawn_time="295">
					<spot x="1019" y="665.5" z="310.75" h="30"/>
				</spawn>
				<!-- Karsinus Warehouse Manager -->
				<spawn npc_id="801157" handler="MERCHANT" respawn_time="295">
					<spot x="1005.5" y="661" z="310.75" h="15"/>
				</spawn>
				<!-- Callias Administration Officer -->
				<spawn npc_id="801158" handler="MERCHANT" respawn_time="295">
					<spot x="1010.125" y="660.5" z="310.75" h="30"/>
				</spawn>
			</simple_race>
			<simple_race race="ASMODIANS">
				<!-- Asmodian Territory -->
				<spawn npc_id="701800" handler="FLAG">
					<spot x="1010.0192" y="664.5961" z="309.7885" h="30"/>
				</spawn>
				<!-- Territory Boss -->
				<spawn npc_id="231551" handler="BOSS">
					<spot x="1015.625" y="661.875" z="309.99072" h="60"/>
				</spawn>
				<!-- Asmodian Eltnen Inspector (possible for Quest?) -->
				<spawn npc_id="231615" handler="ATTACKER">
					<spot x="982.75" y="701" z="304.83594" h="105"/>
				</spawn>
				<!-- Eltnen Infiltrator -->
				<spawn npc_id="231586" handler="SENTINEL" respawn_time="295">
					<spot x="1012.8298" y="676.36615" z="307.3939" h="30"/>
					<spot x="1017.625" y="674.875" z="307.03766" h="30"/>
					<spot x="1000.875" y="668.125" z="307.4504" h="60"/>
					<spot x="1000.375" y="663.625" z="308.1136" h="60"/>
				</spawn>
				<!-- Hastein General Goods -->
				<spawn npc_id="801159" handler="MERCHANT" respawn_time="295">
					<spot x="1019" y="665.5" z="310.75" h="30"/>
				</spawn>
				<!-- Tulus Warehouse Manager -->
				<spawn npc_id="801160" handler="MERCHANT" respawn_time="295">
					<spot x="1005.5" y="661" z="310.75" h="15"/>
				</spawn>
				<!-- Donar Administration Officer -->
				<spawn npc_id="801161" handler="MERCHANT" respawn_time="295">
					<spot x="1010.125" y="660.5" z="310.75" h="30"/>
				</spawn>
			</simple_race>
			<simple_race race="NPC">
				<!-- Lepharist Territory -->
				<spawn npc_id="701796" handler="FLAG">
					<spot x="1010.0192" y="664.5961" z="309.7885" h="30"/>
				</spawn>
				<!-- Territory Boss -->
				<spawn npc_id="231549" handler="BOSS">
					<spot x="1015.625" y="661.875" z="309.99072" h="60"/>
				</spawn>
				<!-- Lepharist Assassin -->
				<spawn npc_id="231606" handler="ATTACKER">
					<spot x="1013.875" y="661.875" z="309.97656"/>
				</spawn>
				<!-- Lepharist Vanguard (Shieldcaptain) -->
				<spawn npc_id="231598" handler="SENTINEL" respawn_time="295">
					<spot x="981.9657" y="702.1578" z="302.24228" h="101"/>
				</spawn>
				<!-- Lepharist Protector -->
				<spawn npc_id="231573" handler="SENTINEL" respawn_time="295">
					<spot x="1000.375" y="663.625" z="307.3246" h="60"/>
					<spot x="1000.875" y="668.125" z="307.3246" h="60"/>
					<spot x="1012.8298" y="676.36615" z="306.99368" h="30"/>
					<spot x="1017.625" y="674.875" z="306.99368" h="30"/>
				</spawn>
			</simple_race>
		</base_spawn>
	</spawn_map>
</spawns>
