=== beyond-aion/aion-server/game-server/data/static_data/skills/alias_locations.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="alias_locations" type="AliasLocations" />
	<xs:complexType name="AliasLocations">
		<xs:sequence>
			<xs:element name="alias_location" type="AliasLocation" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AliasLocation">
		<xs:sequence>
			<xs:element name="alias_pos" type="AliasPosition" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="world_id" type="xs:int" use="required"/>
	</xs:complexType>
	<xs:complexType name="AliasPosition">
		<xs:attribute name="x" type="xs:float" use="required"/>
		<xs:attribute name="y" type="xs:float" use="required"/>
		<xs:attribute name="z" type="xs:float" use="required"/>
		<xs:attribute name="h" type="xs:byte" default="0"/> <!-- retail: dir (degrees, h = dir / 3) -->
	</xs:complexType>
</xs:schema>

=== beyond-aion/aion-server/game-server/data/static_data/skills/alias_locations.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<alias_locations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="alias_locations.xsd">
	<!-- Lower Udas Temple-->
	<alias_location name="IDTemple_Low_Furnace_01" world_id="300160000">
		<alias_pos x="529.252380" y="1297.261719" z="198" h="0"/>
		<alias_pos x="530.399963" y="1298.903198" z="198" h="0"/>
	</alias_location>
	<!-- Transidium_Annex -->
	<alias_location name="Alias_5" world_id="400030000">
		<alias_pos x="488.077454" y="561.374023" z="680.617981" h="0"/>
		<alias_pos x="557.602478" y="534.414490" z="680.617981" h="0"/>
		<alias_pos x="461.459229" y="491.717529" z="680.617981" h="0"/>
		<alias_pos x="530.657043" y="465.133209" z="680.617981" h="0"/>
	</alias_location>
</alias_locations>
