=== beyond-aion/aion-server/game-server/data/static_data/skills/signet_data_templates.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="signet_data_templates" type="SignetDataTemplates"/>
	<xs:complexType name="SignetDataTemplates">
		<xs:sequence>
			<xs:element name="signet_data_template" type="SignetDataTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SignetDataTemplate">
		<xs:sequence>
			<xs:element name="signet_data" type="SignetData" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="signet_skill" type="SignetEnum" use="required"/>
	</xs:complexType>
	<xs:complexType name="SignetData">
		<xs:attribute name="lvl" type="xs:int" use="required"/>
		<xs:attribute name="carve_prob" type="xs:int" default="100"/>
		<xs:attribute name="add_effect_prob" type="xs:int" default="1" />
		<xs:attribute name="dmg_multi" type="xs:float" use="required"/>
	</xs:complexType>
	<xs:simpleType name="SignetEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SIGNET1"/>
			<xs:enumeration value="SIGNET2"/>
			<xs:enumeration value="SIGNET3"/>
			<xs:enumeration value="SIGNET4"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== beyond-aion/aion-server/game-server/data/static_data/skills/signet_data_templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<signet_data_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signet_data_templates.xsd">
	<signet_data_template signet_skill="SIGNET1">
		<signet_data lvl="0" add_effect_prob="0" dmg_multi="0.1"/>
		<signet_data lvl="1" add_effect_prob="0" dmg_multi="0.2"/>
		<signet_data lvl="2" add_effect_prob="20" dmg_multi="0.5"/>
		<signet_data lvl="3" add_effect_prob="50" dmg_multi="1.0"/>
		<signet_data lvl="4" add_effect_prob="70" dmg_multi="1.2"/>
		<signet_data lvl="5" add_effect_prob="100" dmg_multi="1.5"/>
	</signet_data_template>
	<signet_data_template signet_skill="SIGNET2">
		<signet_data lvl="0" add_effect_prob="1" dmg_multi="0.12"/>
		<signet_data lvl="1" add_effect_prob="1" dmg_multi="0.3"/>
		<signet_data lvl="2" add_effect_prob="1" dmg_multi="0.5"/>
		<signet_data lvl="3" add_effect_prob="1" dmg_multi="0.7"/>
		<signet_data lvl="4" add_effect_prob="1" dmg_multi="0.9"/>
		<signet_data lvl="5" add_effect_prob="1" dmg_multi="1.1"/>
	</signet_data_template>
	<signet_data_template signet_skill="SIGNET3">
		<signet_data lvl="0" add_effect_prob="1" dmg_multi="0.12"/>
		<signet_data lvl="1" add_effect_prob="1" dmg_multi="0.5"/>
		<signet_data lvl="2" add_effect_prob="1" dmg_multi="0.9"/>
		<signet_data lvl="3" add_effect_prob="1" dmg_multi="1.1"/>
		<signet_data lvl="4" add_effect_prob="1" dmg_multi="1.3"/>
		<signet_data lvl="5" add_effect_prob="1" dmg_multi="1.5"/>
	</signet_data_template>
	<signet_data_template signet_skill="SIGNET4">
		<signet_data lvl="0" add_effect_prob="1" dmg_multi="0.12"/>
		<signet_data lvl="1" add_effect_prob="1" dmg_multi="0.5"/>
		<signet_data lvl="2" add_effect_prob="1" dmg_multi="0.9"/>
		<signet_data lvl="3" add_effect_prob="1" dmg_multi="1.1"/>
		<signet_data lvl="4" add_effect_prob="1" dmg_multi="1.3"/>
		<signet_data lvl="5" add_effect_prob="1" dmg_multi="1.5"/>
	</signet_data_template>
</signet_data_templates>
